### PR TITLE
Add new command to get device status

### PR DESCRIPTION
**Pull request by hftsai256**
API reference: https://github.com/banzalik/homebridge-winix-c545/blob/master/index.js

### CODE REVIEW

**Comment by hfern** [comment]
@hftsai256 This looks great and thank you for the feature! The only thing I can see is that it needs code reformatting on it. If you just run `make fmt` (alternatively: `pip install black && black winix`) that should do it.

Once you do that I will merge and cut a release to pip.

I will look at Github Actions and see if I can have that run that check so it's more obvious next time.

Thank you again!

**Comment by hfern** [comment]
@hftsai256 I've added a linting check. Can you rebase from master and then run `make fmt` to reformat the code?

I've left the master branch in a failing state so that you won't have to resolve conflicts. Once you merge your formatted PR this should be fixed.

Thanks again for the contribution!

**Comment by hftsai256** [comment]
I've done the format with `black`. This is a really interesting integration infrastructure I haven't seen before, and I feel I should introduce it into my other projects. Thanks man

**Comment by hfern** [comment]
It's my first time using Github Actions and I *think* I did not set it up correctly, as I believe it should have shown the CI status on this PR page after you rebased your PR. 🤷 I'll have to look into it.

Thanks again @hftsai256 for your contribution! I've released it as `0.2.1` and you can install it via pip with `pip install winix==0.2.1`.

https://pypi.org/project/winix/0.2.1/

**Pull request merged**
