### PR TITLE
Add support for sleep mode, manual/auto modes, and plasmawave on/off

### PR DESCRIPTION
**Pull request by dgsharpe**

### CODE REVIEW

**Comment by dgsharpe** [comment]
While doing this I noticed the "TODO" for getting the current fan state. I didn't implement that here because I don't have a need for it, but I did discover how to do it. Here's what I found, in case you hadn't discovered this already. 

Sending a GET request to `https://us.api.winix-iot.com/common/event/sttus/devices/{deviceid}` returns a body that looks like this:

`{"statusCode":200,"headers":{"resultCode":"S100","resultMessage":""},"body":{"deviceId":"REDACTED","totalCnt":1,"data":[{"apiNo":"A210","apiGroup":"001","deviceGroup":"Air01","modelId":"C545","attributes":{"A02":"1","A03":"02","A04":"01","A05":"01","A07":"0","A21":"REDACTED","S07":"REDACTED","S08":"REDACTED","S14":"19"},"rssi":"REDACTED","creationTime":REDACTED,"utcDatetime":"REDACTED","utcTimestamp":REDACTED}]}}`

Apologies for the redactions, but not sure how Winix feels about this repo and wouldn't want to draw their attention to my particular unit. Obviously this can be trivially parsed, it uses the same keys and values that you already support for setting operations.

The items in 'attributes' you see here which aren't yet supported in this repo are as follows:
A05: aqi (air quality index of the location where the filter is registered)
A21: filter (I'm guessing this is the number of hours of use on that filter)
S07: gas level (relates to the filter's built-in gas sensor, but not sure what this measures exactly)
S08: gas value (see above)
S14: light (don't know what this means specifically)

**Comment by hfern** [comment]
This repo is very unofficial :)

Looks great and thanks for the contrib!

Re: the sstus I already have a branch working on exposing device status. Not sure how I want to do it yet.

I'll update the package on PyPI shortly.

**Comment by hfern** [comment]
Version published as `winix==0.1.1` -- see https://pypi.org/project/winix/0.1.1/

**Comment by hftsai256** [comment]
> While doing this I noticed the "TODO" for getting the current fan state. I didn't implement that here because I don't have a need for it, but I did discover how to do it. Here's what I found, in case you hadn't discovered this already.
> 
> Sending a GET request to `https://us.api.winix-iot.com/common/event/sttus/devices/{deviceid}` returns a body that looks like this:
> 
> `{"statusCode":200,"headers":{"resultCode":"S100","resultMessage":""},"body":{"deviceId":"REDACTED","totalCnt":1,"data":[{"apiNo":"A210","apiGroup":"001","deviceGroup":"Air01","modelId":"C545","attributes":{"A02":"1","A03":"02","A04":"01","A05":"01","A07":"0","A21":"REDACTED","S07":"REDACTED","S08":"REDACTED","S14":"19"},"rssi":"REDACTED","creationTime":REDACTED,"utcDatetime":"REDACTED","utcTimestamp":REDACTED}]}}`
> 
> Apologies for the redactions, but not sure how Winix feels about this repo and wouldn't want to draw their attention to my particular unit. Obviously this can be trivially parsed, it uses the same keys and values that you already support for setting operations.
> 
> The items in 'attributes' you see here which aren't yet supported in this repo are as follows:
> A05: aqi (air quality index of the location where the filter is registered)
> A21: filter (I'm guessing this is the number of hours of use on that filter)
> S07: gas level (relates to the filter's built-in gas sensor, but not sure what this measures exactly)
> S08: gas value (see above)
> S14: light (don't know what this means specifically)

I implemented a new command to fetch device status in PR#3. Thanks for the attributes information.

**Pull request merged**
